AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Clothe to Care static website hosting on S3 with CloudFront'

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket (must be globally unique)
    Default: clothetocare-website
    
  DomainName:
    Type: String
    Description: (Optional) Custom domain name for the website
    Default: ''

Conditions:
  HasDomain: !Not [!Equals [!Ref DomainName, '']]

Resources:
  # S3 Bucket for website hosting
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: ClotheToCore
        - Key: Environment
          Value: Production

  # S3 Bucket Policy for CloudFront access only
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: CloudFrontReadAccess
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}'
            Action: 's3:GetObject'
            Resource: !Sub '${WebsiteBucket.Arn}/*'

  # CloudFront Origin Access Identity
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OAI for ${BucketName}'

  # CloudFront Distribution
  WebsiteCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: Clothe to Care Website Distribution
        DefaultRootObject: index.html
        HttpVersion: http2
        PriceClass: PriceClass_100
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebsiteBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOAI}'
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: '658327ea-f89d-4fab-a63d-7e88639e58f6'  # Managed-CachingOptimized
          OriginRequestPolicyId: '216adef5-5c7f-47e4-b989-5492eafa07d3'  # Managed-CORS-S3Origin
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /404.html
            ErrorCachingMinTTL: 300
        Aliases: !If
          - HasDomain
          - [!Ref DomainName]
          - !Ref AWS::NoValue
      Tags:
        - Key: Project
          Value: ClotheToCore
        - Key: Environment
          Value: Production

Outputs:
  WebsiteURL:
    Description: URL for the website hosted on S3
    Value: !GetAtt WebsiteBucket.WebsiteURL
    
  CloudFrontURL:
    Description: CloudFront distribution URL
    Value: !GetAtt WebsiteCloudFront.DomainName
    
  CloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref WebsiteCloudFront
    
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref WebsiteBucket
